import re

def normalize_team_name(name):
    """统一五大联赛队名：自动去除前缀后缀，所有变体归一到标准名"""
    name = name.strip()
    
    # ========== 第一步：去除所有常见前缀 ==========
    prefixes = [
        r'\bLOSC\b', r'\bAS\b', r'\bUS\b', r'\bSS\b', r'\bRC\b',
        r'\bCA\b', r'\bUD\b', r'\bOGC\b', r'\bTSG\b', r'\bSC\b',
        r'\bSV\b', r'\b1\. FC\b', r'\bFC\b', r'\bAFC\b', r'\bCF\b',
        r'\bSAD\b', r'\bSRL\b', r'\b04\b', r'\b07\b', r'\b98\b',
        r'\b1909\b', r'\b1913\b', r'\b1901\b'
    ]
    for p in prefixes:
        name = re.sub(p, '', name)
    
    # ========== 第二步：清理特殊字符和空格 ==========
    name = re.sub(r'[^\w\s&]', ' ', name)
    name = re.sub(r'\s+', ' ', name).strip()
    
    # ========== 第三步：核心队名映射（所有变体 → 标准名） ==========
    name_map = {
        # 英超
        "manchester city": "Manchester City FC",
        "man city": "Manchester City FC",
        "arsenal": "Arsenal FC",
        "liverpool": "Liverpool FC",
        "chelsea": "Chelsea FC",
        "manchester united": "Manchester United FC",
        "man utd": "Manchester United FC",
        "tottenham hotspur": "Tottenham Hotspur FC",
        "spurs": "Tottenham Hotspur FC",
        "newcastle united": "Newcastle United FC",
        "newcastle": "Newcastle United FC",
        "brighton hove albion": "Brighton & Hove Albion FC",
        "brighton": "Brighton & Hove Albion FC",
        "aston villa": "Aston Villa FC",
        "west ham united": "West Ham United FC",
        "west ham": "West Ham United FC",
        "everton": "Everton FC",
        "wolverhampton wanderers": "Wolverhampton Wanderers FC",
        "wolves": "Wolverhampton Wanderers FC",
        "crystal palace": "Crystal Palace FC",
        "fulham": "Fulham FC",
        "brentford": "Brentford FC",
        "leeds united": "Leeds United FC",
        "leeds": "Leeds United FC",
        "leicester city": "Leicester City FC",
        "leicester": "Leicester City FC",
        "southampton": "Southampton FC",
        "nottingham forest": "Nottingham Forest FC",
        "nottingham": "Nottingham Forest FC",
        "bournemouth": "AFC Bournemouth",
        "luton town": "Luton Town FC",
        "luton": "Luton Town FC",
        "burnley": "Burnley FC",
        "sheffield united": "Sheffield United FC",
        "ipswich town": "Ipswich Town FC",
        "coventry city": "Coventry City FC",
        "sunderland": "Sunderland AFC",
        "hull city": "Hull City AFC",

        # 西甲
        "real madrid": "Real Madrid CF",
        "barcelona": "FC Barcelona",
        "barca": "FC Barcelona",
        "atletico madrid": "Atlético Madrid",
        "sevilla": "Sevilla FC",
        "real sociedad": "Real Sociedad",
        "real betis": "Real Betis Balompié",
        "betis": "Real Betis Balompié",
        "villarreal": "Villarreal CF",
        "valencia": "Valencia CF",
        "athletic bilbao": "Athletic Club",
        "osasuna": "CA Osasuna",
        "rayo vallecano": "Rayo Vallecano de Madrid",
        "espanyol": "RCD Espanyol de Barcelona",
        "getafe": "Getafe CF",
        "cadiz": "Cádiz CF",
        "almeria": "UD Almería",
        "granada": "Granada CF",
        "celta vigo": "RC Celta de Vigo",
        "celta": "RC Celta de Vigo",
        "mallorca": "RCD Mallorca",
        "girona": "Girona FC",
        "alaves": "Deportivo Alavés",
        "las palmas": "UD Las Palmas",
        "leganes": "CD Leganés",
        "malaga": "Málaga CF",
        "levante": "Levante UD",
        "la coruna": "RC Deportivo La Coruña",
        "santander": "Real Racing Club de Santander",

        # 德甲
        "bayern munchen": "FC Bayern München",
        "bayern": "FC Bayern München",
        "borussia dortmund": "Borussia Dortmund",
        "dortmund": "Borussia Dortmund",
        "bvb": "Borussia Dortmund",
        "rb leipzig": "RB Leipzig",
        "leipzig": "RB Leipzig",
        "bayer leverkusen": "Bayer 04 Leverkusen",
        "leverkusen": "Bayer 04 Leverkusen",
        "eintracht frankfurt": "Eintracht Frankfurt",
        "frankfurt": "Eintracht Frankfurt",
        "wolfsburg": "VfL Wolfsburg",
        "borussia monchengladbach": "Borussia Mönchengladbach",
        "gladbach": "Borussia Mönchengladbach",
        "mainz": "1. FSV Mainz 05",
        "freiburg": "SC Freiburg",
        "hoffenheim": "TSG 1899 Hoffenheim",
        "union berlin": "1. FC Union Berlin",
        "stuttgart": "VfB Stuttgart",
        "augsburg": "FC Augsburg",
        "werder bremen": "SV Werder Bremen",
        "bremen": "SV Werder Bremen",
        "koln": "1. FC Köln",
        "cologne": "1. FC Köln",
        "schalke": "FC Schalke 04",
        "hertha berlin": "Hertha BSC",
        "hertha": "Hertha BSC",
        "bochum": "VfL Bochum",
        "heidenheim": "1. FC Heidenheim",
        "darmstadt": "Darmstadt 98",
        "holstein kiel": "Holstein Kiel",
        "kiel": "Holstein Kiel",
        "st pauli": "FC St. Pauli",
        "elversberg": "SV 07 Elversberg",
        "paderborn": "SC Paderborn 07",
        "hamburg": "Hamburger SV",

        # 意甲
        "juventus": "Juventus FC",
        "juve": "Juventus FC",
        "ac milan": "AC Milan",
        "milan": "AC Milan",
        "internazionale": "FC Internazionale Milano",
        "inter": "FC Internazionale Milano",
        "napoli": "SSC Napoli",
        "roma": "AS Roma",
        "lazio": "SS Lazio",
        "atalanta": "Atalanta BC",
        "fiorentina": "ACF Fiorentina",
        "torino": "Torino FC",
        "bologna": "Bologna FC 1909",
        "udinese": "Udinese Calcio",
        "sassuolo": "US Sassuolo Calcio",
        "verona": "Hellas Verona FC",
        "lecce": "US Lecce",
        "cagliari": "Cagliari Calcio",
        "empoli": "Empoli FC",
        "genoa": "Genoa CFC",
        "salernitana": "US Salernitana",
        "frosinone": "Frosinone Calcio",
        "monza": "AC Monza",
        "parma": "Parma Calcio 1913",
        "como": "Como 1907",
        "venezia": "Venezia FC",

        # 法甲
        "paris saint germain": "Paris Saint-Germain FC",
        "psg": "Paris Saint-Germain FC",
        "marseille": "Olympique de Marseille",
        "lyon": "Olympique Lyonnais",
        "monaco": "AS Monaco FC",
        "lille": "LOSC Lille",
        "rennes": "Stade Rennais FC",
        "nice": "OGC Nice",
        "strasbourg": "RC Strasbourg Alsace",
        "nantes": "FC Nantes",
        "montpellier": "Montpellier HSC",
        "brest": "Stade Brestois 29",
        "reims": "Stade de Reims",
        "lorient": "FC Lorient",
        "clermont": "Clermont Foot",
        "toulouse": "Toulouse FC",
        "auxerre": "AJ Auxerre",
        "angers": "Angers SCO",
        "metz": "FC Metz",
        "lens": "RC Lens",
        "le havre": "Le Havre AC",
        "havre": "Le Havre AC",
        "saint etienne": "AS Saint-Étienne",
        "caen": "Stade Malherbe Caen",
        "bordeaux": "FC Girondins de Bordeaux",
        "troyes": "ES Troyes AC",
        "dijon": "Dijon FCO",
        "le mans": "Le Mans FC",
        "paris fc": "Paris FC",
    }
    
    key = name.lower().strip()
    if key in name_map:
        return name_map[key]
    
    # 兜底返回
    return name.title()
