# team_config.py
# 统一球队名称映射，所有脚本共用

# 所有已知输入变体 → 标准名称
TEAM_NAME_MAP = {
    # ==================== 英超 ====================
    # football-data.org API 返回的全名
    "Ipswich Town FC": "Ipswich Town FC",
    "Liverpool FC": "Liverpool FC",
    "Manchester City FC": "Manchester City FC",
    "Arsenal FC": "Arsenal FC",
    "Chelsea FC": "Chelsea FC",
    "Manchester United FC": "Manchester United FC",
    "Tottenham Hotspur FC": "Tottenham Hotspur FC",
    "Newcastle United FC": "Newcastle United FC",
    "Brighton & Hove Albion FC": "Brighton & Hove Albion FC",
    "Aston Villa FC": "Aston Villa FC",
    "West Ham United FC": "West Ham United FC",
    "Everton FC": "Everton FC",
    "Wolverhampton Wanderers FC": "Wolverhampton Wanderers FC",
    "Crystal Palace FC": "Crystal Palace FC",
    "Fulham FC": "Fulham FC",
    "Brentford FC": "Brentford FC",
    "Leeds United FC": "Leeds United FC",
    "Leicester City FC": "Leicester City FC",
    "Southampton FC": "Southampton FC",
    "Nottingham Forest FC": "Nottingham Forest FC",
    "AFC Bournemouth": "AFC Bournemouth",
    "Luton Town FC": "Luton Town FC",
    "Burnley FC": "Burnley FC",
    "Sheffield United FC": "Sheffield United FC",
    "Coventry City FC": "Coventry City FC",
    "Sunderland AFC": "Sunderland AFC",
    "Hull City AFC": "Hull City AFC",
    # football-data.co.uk CSV 短名
    "Ipswich": "Ipswich Town FC",
    "Liverpool": "Liverpool FC",
    "Man City": "Manchester City FC",
    "Manchester City": "Manchester City FC",
    "Arsenal": "Arsenal FC",
    "Chelsea": "Chelsea FC",
    "Man United": "Manchester United FC",
    "Manchester United": "Manchester United FC",
    "Tottenham": "Tottenham Hotspur FC",
    "Spurs": "Tottenham Hotspur FC",
    "Newcastle": "Newcastle United FC",
    "Brighton": "Brighton & Hove Albion FC",
    "Aston Villa": "Aston Villa FC",
    "West Ham": "West Ham United FC",
    "Everton": "Everton FC",
    "Wolves": "Wolverhampton Wanderers FC",
    "Crystal Palace": "Crystal Palace FC",
    "Fulham": "Fulham FC",
    "Brentford": "Brentford FC",
    "Leeds": "Leeds United FC",
    "Leicester": "Leicester City FC",
    "Southampton": "Southampton FC",
    "Nott'm Forest": "Nottingham Forest FC",
    "Nottingham Forest": "Nottingham Forest FC",
    "Bournemouth": "AFC Bournemouth",
    "Luton": "Luton Town FC",
    "Burnley": "Burnley FC",
    "Sheffield Utd": "Sheffield United FC",
    "Coventry": "Coventry City FC",
    "Sunderland": "Sunderland AFC",
    "Hull": "Hull City AFC",

    # ==================== 西甲 ====================
    # API 全名
    "Real Madrid CF": "Real Madrid CF",
    "FC Barcelona": "FC Barcelona",
    "Club Atlético de Madrid": "Atlético Madrid",
    "Atlético Madrid": "Atlético Madrid",
    "Sevilla FC": "Sevilla FC",
    "Real Sociedad": "Real Sociedad",
    "Real Sociedad de Fútbol": "Real Sociedad",
    "Real Betis Balompié": "Real Betis Balompié",
    "Villarreal CF": "Villarreal CF",
    "Valencia CF": "Valencia CF",
    "Athletic Club": "Athletic Club",
    "CA Osasuna": "CA Osasuna",
    "Rayo Vallecano de Madrid": "Rayo Vallecano de Madrid",
    "RCD Espanyol de Barcelona": "RCD Espanyol de Barcelona",
    "Getafe CF": "Getafe CF",
    "Cádiz CF": "Cádiz CF",
    "UD Almería": "UD Almería",
    "Granada CF": "Granada CF",
    "RC Celta de Vigo": "RC Celta de Vigo",
    "RCD Mallorca": "RCD Mallorca",
    "Girona FC": "Girona FC",
    "Deportivo Alavés": "Deportivo Alavés",
    "UD Las Palmas": "UD Las Palmas",
    "CD Leganés": "CD Leganés",
    "Málaga CF": "Málaga CF",
    "Levante UD": "Levante UD",
    "RC Deportivo La Coruña": "RC Deportivo La Coruña",
    "Real Racing Club de Santander": "Real Racing Club de Santander",
    # CSV 短名
    "Celta de Vigo": "RC Celta de Vigo",
    "Real Sociedad de Futbol": "Real Sociedad",
    "Real Madrid": "Real Madrid CF",
    "Barcelona": "FC Barcelona",
    "Barca": "FC Barcelona",
    "Atletico Madrid": "Atlético Madrid",
    "Ath Madrid": "Atlético Madrid",
    "Sevilla": "Sevilla FC",
    "Real Betis": "Real Betis Balompié",
    "Betis": "Real Betis Balompié",
    "Villarreal": "Villarreal CF",
    "Valencia": "Valencia CF",
    "Athletic Bilbao": "Athletic Club",
    "Osasuna": "CA Osasuna",
    "Rayo Vallecano": "Rayo Vallecano de Madrid",
    "Espanyol": "RCD Espanyol de Barcelona",
    "Getafe": "Getafe CF",
    "Cadiz": "Cádiz CF",
    "Almeria": "UD Almería",
    "Granada": "Granada CF",
    "Celta Vigo": "RC Celta de Vigo",
    "Celta": "RC Celta de Vigo",
    "Mallorca": "RCD Mallorca",
    "Girona": "Girona FC",
    "Alaves": "Deportivo Alavés",
    "Las Palmas": "UD Las Palmas",
    "Leganes": "CD Leganés",
    "Malaga": "Málaga CF",
    "Levante": "Levante UD",
    "La Coruna": "RC Deportivo La Coruña",
    "Santander": "Real Racing Club de Santander",

    # ==================== 德甲 ====================
    # API 全名
    "FC Bayern München": "FC Bayern München",
    "Borussia Dortmund": "Borussia Dortmund",
    "RB Leipzig": "RB Leipzig",
    "Bayer 04 Leverkusen": "Bayer 04 Leverkusen",
    "Eintracht Frankfurt": "Eintracht Frankfurt",
    "VfL Wolfsburg": "VfL Wolfsburg",
    "Borussia Mönchengladbach": "Borussia Mönchengladbach",
    "1. FSV Mainz 05": "1. FSV Mainz 05",
    "SC Freiburg": "SC Freiburg",
    "TSG 1899 Hoffenheim": "TSG 1899 Hoffenheim",
    "1. FC Union Berlin": "1. FC Union Berlin",
    "VfB Stuttgart": "VfB Stuttgart",
    "FC Augsburg": "FC Augsburg",
    "SV Werder Bremen": "SV Werder Bremen",
    "1. FC Köln": "1. FC Köln",
    "1 FC Köln": "1. FC Köln",
    "FC Schalke 04": "FC Schalke 04",
    "Hertha BSC": "Hertha BSC",
    "VfL Bochum": "VfL Bochum",
    "1. FC Heidenheim": "1. FC Heidenheim",
    "Darmstadt 98": "Darmstadt 98",
    "Holstein Kiel": "Holstein Kiel",
    "FC St. Pauli": "FC St. Pauli",
    "SV 07 Elversberg": "SV 07 Elversberg",
    "SC Paderborn 07": "SC Paderborn 07",
    "Hamburger SV": "Hamburger SV",
    # CSV 短名
    "Bayern Munich": "FC Bayern München",
    "Bayern": "FC Bayern München",
    "Dortmund": "Borussia Dortmund",
    "BVB": "Borussia Dortmund",
    "Leipzig": "RB Leipzig",
    "Leverkusen": "Bayer 04 Leverkusen",
    "Frankfurt": "Eintracht Frankfurt",
    "Wolfsburg": "VfL Wolfsburg",
    "Gladbach": "Borussia Mönchengladbach",
    "B M'gladbach": "Borussia Mönchengladbach",
    "Mainz": "1. FSV Mainz 05",
    "Freiburg": "SC Freiburg",
    "Hoffenheim": "TSG 1899 Hoffenheim",
    "Union Berlin": "1. FC Union Berlin",
    "Stuttgart": "VfB Stuttgart",
    "Augsburg": "FC Augsburg",
    "Werder Bremen": "SV Werder Bremen",
    "Bremen": "SV Werder Bremen",
    "Köln": "1. FC Köln",
    "Koln": "1. FC Köln",
    "Cologne": "1. FC Köln",
    "Schalke 04": "FC Schalke 04",
    "Schalke": "FC Schalke 04",
    "Hertha Berlin": "Hertha BSC",
    "Hertha": "Hertha BSC",
    "Bochum": "VfL Bochum",
    "Heidenheim": "1. FC Heidenheim",
    "Darmstadt": "Darmstadt 98",
    "Kiel": "Holstein Kiel",
    "St Pauli": "FC St. Pauli",
    "Elversberg": "SV 07 Elversberg",
    "Paderborn": "SC Paderborn 07",
    "Hamburg": "Hamburger SV",

    # ==================== 意甲 ====================
    # API 全名
    "Juventus FC": "Juventus FC",
    "AC Milan": "AC Milan",
    "FC Internazionale Milano": "FC Internazionale Milano",
    "SSC Napoli": "SSC Napoli",
    "AS Roma": "AS Roma",
    "SS Lazio": "SS Lazio",
    "Atalanta BC": "Atalanta BC",
    "ACF Fiorentina": "ACF Fiorentina",
    "Torino FC": "Torino FC",
    "Bologna FC 1909": "Bologna FC 1909",
    "Udinese Calcio": "Udinese Calcio",
    "US Sassuolo Calcio": "US Sassuolo Calcio",
    "Hellas Verona FC": "Hellas Verona FC",
    "US Lecce": "US Lecce",
    "Cagliari Calcio": "Cagliari Calcio",
    "Empoli FC": "Empoli FC",
    "Genoa CFC": "Genoa CFC",
    "US Salernitana": "US Salernitana",
    "Frosinone Calcio": "Frosinone Calcio",
    "AC Monza": "AC Monza",
    "Parma Calcio 1913": "Parma Calcio 1913",
    "Como 1907": "Como 1907",
    "Venezia FC": "Venezia FC",
    # CSV 短名
    "Juventus": "Juventus FC",
    "Juve": "Juventus FC",
    "Milan": "AC Milan",
    "Inter": "FC Internazionale Milano",
    "Inter Milan": "FC Internazionale Milano",
    "Napoli": "SSC Napoli",
    "Roma": "AS Roma",
    "Lazio": "SS Lazio",
    "Atalanta": "Atalanta BC",
    "Fiorentina": "ACF Fiorentina",
    "Torino": "Torino FC",
    "Bologna": "Bologna FC 1909",
    "Udinese": "Udinese Calcio",
    "Sassuolo": "US Sassuolo Calcio",
    "Verona": "Hellas Verona FC",
    "Lecce": "US Lecce",
    "Cagliari": "Cagliari Calcio",
    "Empoli": "Empoli FC",
    "Genoa": "Genoa CFC",
    "Salernitana": "US Salernitana",
    "Frosinone": "Frosinone Calcio",
    "Monza": "AC Monza",
    "Parma": "Parma Calcio 1913",
    "Como": "Como 1907",
    "Venezia": "Venezia FC",

    # ==================== 法甲 ====================
    # API 全名
    "Paris Saint-Germain FC": "Paris Saint-Germain FC",
    "Paris Saint Germain FC": "Paris Saint-Germain FC",
    "Olympique de Marseille": "Olympique de Marseille",
    "Olympique Lyonnais": "Olympique Lyonnais",
    "AS Monaco FC": "AS Monaco FC",
    "LOSC Lille": "LOSC Lille",
    "Lille OSC": "LOSC Lille",
    "Stade Rennais FC": "Stade Rennais FC",
    "Stade Rennais FC 1901": "Stade Rennais FC",
    "OGC Nice": "OGC Nice",
    "RC Strasbourg Alsace": "RC Strasbourg Alsace",
    "FC Nantes": "FC Nantes",
    "Montpellier HSC": "Montpellier HSC",
    "Stade Brestois 29": "Stade Brestois 29",
    "Stade de Reims": "Stade de Reims",
    "FC Lorient": "FC Lorient",
    "Clermont Foot": "Clermont Foot",
    "Toulouse FC": "Toulouse FC",
    "AJ Auxerre": "AJ Auxerre",
    "Angers SCO": "Angers SCO",
    "FC Metz": "FC Metz",
    "RC Lens": "RC Lens",
    "Racing Club de Lens": "RC Lens",
    "Le Havre AC": "Le Havre AC",
    "Havre AC": "Le Havre AC",
    "AS Saint-Étienne": "AS Saint-Étienne",
    "Stade Malherbe Caen": "Stade Malherbe Caen",
    "FC Girondins de Bordeaux": "FC Girondins de Bordeaux",
    "ES Troyes AC": "ES Troyes AC",
    "ESTAC Troyes": "ES Troyes AC",
    "Dijon FCO": "Dijon FCO",
    "Le Mans FC": "Le Mans FC",
    "Paris FC": "Paris FC",
    # CSV 短名
    "Paris SG": "Paris Saint-Germain FC",
    "Paris Saint Germain": "Paris Saint-Germain FC",
    "PSG": "Paris Saint-Germain FC",
    "Marseille": "Olympique de Marseille",
    "Lyon": "Olympique Lyonnais",
    "Monaco": "AS Monaco FC",
    "Lille": "LOSC Lille",
    "Rennes": "Stade Rennais FC",
    "Nice": "OGC Nice",
    "Strasbourg": "RC Strasbourg Alsace",
    "Nantes": "FC Nantes",
    "Montpellier": "Montpellier HSC",
    "Brest": "Stade Brestois 29",
    "Reims": "Stade de Reims",
    "Lorient": "FC Lorient",
    "Clermont": "Clermont Foot",
    "Toulouse": "Toulouse FC",
    "Auxerre": "AJ Auxerre",
    "Angers": "Angers SCO",
    "Metz": "FC Metz",
    "Lens": "RC Lens",
    "Le Havre": "Le Havre AC",
    "Havre": "Le Havre AC",
    "Saint-Etienne": "AS Saint-Étienne",
    "St Etienne": "AS Saint-Étienne",
    "Caen": "Stade Malherbe Caen",
    "Bordeaux": "FC Girondins de Bordeaux",
    "Troyes": "ES Troyes AC",
    "Dijon": "Dijon FCO",
    "Le Mans": "Le Mans FC",
}


def normalize_team_name(name):
    """统一队名：字典精确匹配 → 大小写不敏感匹配 → 原样返回"""
    if not name:
        return name
    name = name.strip()

    # 1. 精确匹配
    if name in TEAM_NAME_MAP:
        return TEAM_NAME_MAP[name]

    # 2. 大小写不敏感匹配
    name_lower = name.lower()
    for key, value in TEAM_NAME_MAP.items():
        if key.lower() == name_lower:
            return value

    # 3. 兜底：原样返回
    return name
